{% set name = "ipyxact" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95651b079befc02f56e3a71e15a03d2a305ef14d419a2b7c2f3cdc484bafc293

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml

test:
  imports:
    - ipyxact

about:
  home: https://github.com/olofk/ipyxact
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python-based IP-XACT parser
  description: |
    ipyxact is a helper library that creates python structures from parsed
    IP-Xact files. It is intended to make it easier to use IP-Xact files in a
    python application

extra:
  recipe-maintainers:
    - hmaarrfk
