{% set name = "ipyxact" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab1757e8870503852a390de34ff3e368be1fd78c2235f34edb8bece9b7eaa36e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - ipyxact
  commands:
    - pip check

about:
  home: https://github.com/olofk/ipyxact
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python-based IP-XACT parser
  description: |
    ipyxact is a helper library that creates python structures from parsed
    IP-Xact files. It is intended to make it easier to use IP-Xact files in a
    python application

extra:
  recipe-maintainers:
    - hmaarrfk
