travis:
  secure:
    BINSTAR_TOKEN: Dm4OwkjGkgyH2gUbQni/o/UNbp1sIqFmKS6Fzx8V/D1mmf9MYlcxi9cvDhImMx400kZ6jYrgENHoF2z7D7y0OlBvXv+FnlD9QJbzumc4WwOrRdIzLRfVQtLSWiqj5kvnnuE1XaOF5I6XaXbEMMY/XoV/QSjGZy079MSPNpj9kbFtb2sJBgeM5XL/uHX1nrgiXpYfaanR56iuxUvI0heXdm1CcKC1p05fIhGa0czlAfqnUynUK60Z5wpmtVnJo3Ebj3+0OTPlOxGCqIGWh3J2ZDgJ0rHa5uuSv4UkNiEahtXka8oSD6CU7F/MnZFuxhfy32sz8PYcc4swaEyCR1tLILA721Nwtitcg+BKmE8nFegpGcTxJ5e8K3Crz6yuUod+Re5UoK3ooTFAajuVAxLNNbeYXkSI++/+i1kUMPxigr6odKxdIkCNJ2WzhiYyX8mZ157pYLS60m5WLr+akGPRFYoWSkJTG5tPGJi5NpiVUz3mUva1QtndhzeWboqppscKqptix/zScPDUKemJRU/z8Qx2mciDkZC1iPF9YwmYIUMh3SpEpfzVrSjMoA9lzepNY5f8397xGEq0AwAKrY4zzc9cSCNooSsonuB3SAKX5cWjYOZ12WVRfwmQILcO/THq5d35qrMk21bzDJb6Ab9b8zpKLbdarI0MV+b5PGV3RoA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
